### ISSUE TITLE
Shape failed because  different `glyph_index` from `ttf-parser` 

### ISSUE THREAD

**Issue by M-Adoo** [RazrFalcon/rustybuzz#48]
In my code, I find a face  across `Face::glyph_index`(ttf-parser) to shape "⚛",  but failed.  I found those different logic between ttf-parser and rustybuzz.

rustybuzz face only resolve glyph id by `prefered_cmap_encoding_subtable`.

```rust 
    pub(crate) fn glyph_index(&self, c: u32) -> Option<GlyphId> {
        let subtable_idx = self.prefered_cmap_encoding_subtable?;
        let subtable = self.tables().cmap?.subtables.get(subtable_idx)?;
        match subtable.glyph_index(c) {
            Some(gid) => Some(gid),
            None => {
             ...
            }
        }
    }
```

And ttf-parser iterate all subtables 
```rust
    pub fn glyph_index(&self, code_point: char) -> Option<GlyphId> {
        for encoding in self.tables.cmap?.subtables {
            if !encoding.is_unicode() {
                continue;
            }

            if let Some(id) = encoding.glyph_index(u32::from(code_point)) {
                return Some(id);
            }
        }

        None
    }
```

Is this a bug?   A font face contain this glyph, but not use to shape it.  Or I should use another way to find suitable font to shape?

**Comment by RazrFalcon** [comment]
This should match [harfbuzz logic](https://github.com/harfbuzz/harfbuzz/blob/f41945e313ca053253bfd339186b87c977da3bf3/src/hb-ot-cmap-table.hh#L1670). So no, this is not a bug.

Why you cannot shape this character is the whole another question. Try (assuming you have harfbuzz installed):
```
hb-shape path-to-your-font.ttf '⚛'
```

**Comment by M-Adoo** [comment]
Thanks, i get it .  In my case, I think we should export  `rustybuzz::Face::glyph_index`, so user can use it to detect if a font  can use to shape their text.  

I can create a pr if you think it is OK.

**Comment by RazrFalcon** [comment]
I will think about making it public. The documentation is the crucial part here.
Also, I'm not sure why hb/rb ignores this cmap table to begin with. Strange.

**Comment by laurmaedje** [comment]
@M-Adoo That would work in many cases. But in general it's difficult to say whether a font can be used to shape a text. For example, the cmap of the font Noto Color Emoji doesn't contain all individual codepoints of the 1️⃣ emoji (it's composed of multiple characters: 1 + variation selector + enclosing keycap), but it can still be used to shape the emoji because the shaper resolves that during normalization. 

It might work the other way around, that shaping works if cmap contains every codepoint (not sure honestly, shaping is complicated). Anyway, detecting it with `glyph_index` might be good enough, but if it's not too expensive for your use case, your best bet might be to just try shaping and then checking whether any glyphs with id 0 result from that.

**Comment by M-Adoo** [comment]
@laurmaedje I'm not try to find a  font  100%  can use to shape text, but exclude the font 100% Impossible to improve performance .

**Comment by RazrFalcon** [comment]
That's the problem. You cannot do this. Shaping is very complicated task and you can't really predict the results beforehand.
As an example, rb/hb will do Unicode normalization and [glyph substitution](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub) after which the input data can already be way different to the source one.

Run the shaper and look for 0 GlyphIDs (as @laurmaedje mentioned). This is the only way.

**Comment by M-Adoo** [comment]
Thanks @RazrFalcon @laurmaedje ,  I didn't think deeply enough. Theoretically a font does not contain any glyphs of chars  not means it can't use to shape the text.
